name: Standard version CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm install standard-version@latest
    - name: Set up git credentials
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - run: npm run release
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      
